### ISSUE TITLE
How do I make the text bold inside a badge icon?

### ISSUE THREAD

**Issue by roman-ku** [volders/Badger#10]

**Comment by tynn** [comment]
You'd have to subclass `TextBadge` or `CountBadge` and override `onPrepareTextPaint(Paint)` to make the `Paint` use a bold `Typeface` like the following.

    @Override
    protected void onPrepareTextPaint(@NonNull Paint paint) {
        super.onPrepareTextPaint(paint);
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
    }
