### ISSUE TITLE
Why it always return primary color. Don't have anyway to change color?

### ISSUE THREAD

**Issue by trinhvanminh2009** [volders/Badger#13]
I'm using getBorderColor(Context context) like sample in your source code. But it always show primary color. Does it have anyway to change color . For example (Badger.setCount(10).setColor()). I trying to using setColorFilter() but not working (have setColorFilter() , setCount() not found).
Hope you help me.

**Comment by tynn** [comment]
It's just a simple example. You'd have to implement getting the right color with `getBorderColor(Context)` by yourself.

**Comment by trinhvanminh2009** [comment]
I got it. Thank you so much !
