### ISSUE TITLE
Adding count on Drawable

### ISSUE THREAD

**Issue by icoolguy1995** [volders/Badger#15]
Hi there! first of all it's a great lib and fun to use. BTW, I am having a problem. I am unable to determine how to set count on a drawable. I have a method which returns drawable to set on view, like this:

```
public Drawable getDrawable(){
Drawable drawable;
//my stuff

return drawable;
}
```
I am unable to set badge in my method, I couldn't find any examples as well. Please help
Thanks!

**Comment by tynn** [comment]
You can do this with `Badger#sett(Drawable,BadgeDrawable.Factory)`:
```
public Drawable getDrawable(){
    Drawable drawable;
    //my stuff - setting up the drawable
    Badger<?> badger = Badger.sett(drawable, badgeFactory);
    BadgeDrawable badge = badger.badge;
    //my stuff - setting up the badge
    return badger.drawable;
}
```

**Comment by icoolguy1995** [comment]
'
'
'

**Comment by icoolguy1995** [comment]
Sorry to bother you again, but I couldn't find any method to set badge count on my drawable. `.setCount(x);` is unresolved for drawables.

**Comment by tynn** [comment]
You need to use a `CountBadge.Factory` and declare `badger` as `Badger<CountBadge>` and `badge` as `CountBadge`.
