### ISSUE TITLE
how to increase the  font size of badge count  and change color of text

### ISSUE THREAD

**Issue by hirenpatel868** [volders/Badger#5]

**Comment by tynn** [comment]
The text color can be set within the factory or directly with the attribute `badgeTextColor`. https://github.com/volders/Badger/blob/master/library/src/main/res/values/attrs.xml

Changing the font size was never intended with the current implementation. `TextBadge` uses a magic scale factor which made sense. If you want to do it differently, you need to implement your own `BadgeDrawable`. How would you like to handle the font size?
